# What's the point?

### Import

In [24]:
import numpy as np

In [1]:
from geom.circl import ppoint, ccircle

### Instantiate and call

A ccircle is created by giving it a centerpoint and radius parameters

In [31]:
c1 = ccircle([6,12,2])
c1

ccircle(
[[ 6 12  2]]
)

We can acces the parameters with getters; For getting the x-coordinate for example we do:

In [15]:
c1.x

array([[6]])

Getting the x and y parametrs at once follows the same principle. 

Note however that by doing so we now also call the superclass, the ppoint.

In [33]:
p1 = c1.xy
p1

ppoint(
 [[ 6 12]]
)

We can off course create a ccirlce from a ppoint and the loop is closed

In [34]:
c1 = ccircle(np.append(p1,2))
c1

ccircle(
[[ 6 12  2]]
)

Note that the ppoint is a subclass of the numpy.ndarray and thus so is the ccircle

In [37]:
c2 = c1 + np.array([2,0,0])
c2

ccircle(
[[ 8 12  2]]
)

We can create a ppoint with multiple coordinates as well. Same goes for ccircles.

In [44]:
c12 = ccircle([[6,12,2]
              ,[8,12,2]])
c12

ccircle(
[[ 6 12  2]
 [ 8 12  2]]
)

Getting the xy coordinates (or any other parameter) follows the same logic as before

In [46]:
c12.xy

ppoint(
[[ 6 12]
 [ 8 12]]
)

### Methods

We can take the distance between two circles (easy):

In [43]:
c1.distance(c2)

array([[2.]])

Or take the distance between a circle and a circle with multiple coordinates

In [66]:
c4.distance(c12)

array([[2.82842712],
       [2.        ]])

We can also do it like this:

In [67]:
c3 = ccircle([6,10,2])
c4 = ccircle([8,10,2])
c1.distance([c2, c3, c4])

array([[2.        ],
       [2.        ],
       [2.82842712]])

For intersection points we follow a similar approach (note that it again results in the superclass ppoint, allowing further analysis)

In [64]:
i1 = c1.intersect(c2)[0] # For the first intersection point
i2 = c1.intersect(c2)[1] # For the second intersection point
i1

ppoint(
[[ 7.         13.73205081]]
)

In [65]:
i1.distance(i2)

array([[3.46410162]])

---

In [70]:
# Up next: intersection areas